# Generated by Django 3.0.5 on 2021-09-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20210906_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
