# Generated by Django 3.0.5 on 2021-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_transhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='acc_no',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
