# Generated by Django 3.0.5 on 2021-09-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_customer_acc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('credited_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Bank.Customer')),
                ('debited_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Bank.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Transhistory',
        ),
    ]
