# Generated by Django 3.0.5 on 2021-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_auto_20210908_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
